improves multi-tx UX: wait for tx confirmation before requesting the next
ethereum/eth2.0-deposit pull request #167
Opened 2020-08-30 22:46 UTC by georgeweiler

2020-08-30 22:51 UTC, georgeweiler commented
This is a pretty repetitive addition but it works. I will likely push up a refactor soon for improving reusability. Happy to do that later if you need this update merged in ASAP  @CarlBeek

2020-08-31 15:58 UTC, georgeweiler commented on src/pages/Transactions/transactionUtils.tsx
> +    // stop calling yourself
updated.

2020-08-31 15:59 UTC, georgeweiler commented
Pushed a small update to improve code quality

2020-09-01 12:57 UTC, CarlBeek commented on src/pages/Transactions/transactionUtils.tsx
> +      );
```suggestion
```

If the user rejects a TX or something goes wrong, we should not continue presenting more TXs. Instead the user can fix the problem (or not) and continue by pressing the "Make N Deposit transactions" at the top of the page

2020-09-01 19:34 UTC, CarlBeek commented
Great work, @georgeweiler!

To clarify what is being done here, currently each deposit launches an instance of the web3 signer (eg Metamask) simultaneously for each deposit. The result is one window per deposit which, if you are making many deposits, results in an unresponsive PC (or even double deposits due to race conditions between the windows). This PR tackles this by iterating through the deposits and only starting a new one once the previous has been signed.

2020-09-01 19:36 UTC, CarlBeek requested changes
One problem I've encountered since this update is that the window with the keys does not fill the width of the page anymore. Can I ask you to take a crack at it @georgeweiler?

![Screenshot 2020-09-01 at 11 38 33 AM](https://user-images.githubusercontent.com/12530043/91897753-0ff4aa00-ec9b-11ea-8146-d1eef3291761.png)

2020-09-03 22:41 UTC, georgeweiler commented
hey @CarlBeek I just pushed a change to solve the loop/rejection issue and the css bug that I was only experiencing on firefox.

2020-09-09 18:45 UTC, CarlBeek approved these changes

2020-09-09 18:45 UTC, merged