select validator updates
ethereum/eth2.0-deposit pull request #173
Opened 2020-09-18 20:06 UTC by georgeweiler

- updates the workflow progress bar to fit extra validator step
- adds "circle" logos for all validator clients
- recycles the OS selector component for validator selection

<img width="1680" alt="Screen Shot 2020-09-18 at 1 11 12 PM" src="https://user-images.githubusercontent.com/15269424/93640622-e214a280-f9c8-11ea-9063-f2b0b48f13e4.png">

2020-09-18 23:41 UTC, Battenfield requested changes
Looks great, we just need to trim everything below installation on the Eth2 instructions:
<img width="583" alt="Screen Shot 2020-09-18 at 4 38 21 PM" src="https://user-images.githubusercontent.com/7051522/93653376-839df300-f9cd-11ea-8790-405aec963e70.png">

The full instructions on the public pages (i.e. https://medalla.launchpad.ethereum.org/lighthouse) will remain the same. We just need to remove the "Key Generation" section and below from the Setup Validator Step.

2020-09-18 23:44 UTC, Battenfield commented
@CarlBeek could you add in copy for the Eth1 nodes?
<img width="1350" alt="Screen Shot 2020-09-18 at 4 35 27 PM" src="https://user-images.githubusercontent.com/7051522/93653485-fdce7780-f9cd-11ea-961a-141f454836ed.png">

2020-09-21 05:25 UTC, Battenfield approved these changes

2020-09-21 08:21 UTC, CarlBeek commented
For posterity reasons I am reposing the content link I posted in our Telegram chat with the Eth1 content:
https://notes.ethereum.org/@av80r/S1S_HrGBP

2020-09-21 15:22 UTC, flamingYawn approved these changes

2020-09-21 21:02 UTC, merged