adds rainbow footer too the launch pad
ethereum/eth2.0-deposit pull request #224
Opened 2020-10-20 23:25 UTC by georgeweiler

<img width="650" alt="Screen Shot 2020-10-20 at 4 23 31 PM" src="https://user-images.githubusercontent.com/15269424/96654745-d3cfe400-12f0-11eb-8fc1-838f0a86beb9.png">
![Uploading Screen Shot 2020-10-20 at 4.23.10 PM.png…]()

2020-10-20 23:27 UTC, georgeweiler commented
@CarlBeek @hwwhww Last I heard we are still waiting for legal copy confirmation on this?

2020-10-21 01:43 UTC, georgeweiler commented on src/components/Footer.tsx
> +          <Link external to="http://activate.codefi.network/eth2">
something to note: this page will not go live until the EF mainnet launch

2020-10-21 02:29 UTC, hwwhww commented
@georgeweiler RWD design looks good! 👍 

We are still waiting for the policy page content. *If* we need links for multiple static pages (e.g., "Privacy policy", "Terms of Use"), can we replace the "Ethereum 2 Launchpad" column with new pages?

By the way, where does "A Contribution 'originates' from a designated place, then offering..." come from? Is it a stub?

2020-10-22 16:20 UTC, Battenfield requested changes
Let's repleace the previous dark blue footer on the homepage for the new 🌈

2020-11-04 13:16 UTC, hwwhww commented
It seems this PR is replaced by #231 ?

2020-11-04 16:58 UTC, georgeweiler commented
closing, because this is replaced by #231

2020-11-04 16:58 UTC, closed without merging